apiVersion: v1
kind: Service
metadata:
  labels:
    app: daytrader-web-react-npm
  name: daytrader-web-react-npm
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: daytrader-web-react-npm
  #sessionAffinity: ClientIP
#  type: NodePort
  type: LoadBalancer
