apiVersion: v1
kind: Service
metadata:
  labels:
    app: daytrader-scdf-trade-processor
  name: daytrader-scdf-trade-processor
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 6453
  selector:
    app: daytrader-scdf-trade-processor
  sessionAffinity: ClientIP
#  type: LoadBalancer 
