trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: S3Upload@1
  inputs:
    awsCredentials: 'S3-Upload'
    bucketName: 'ss-poc-daytrader'
    sourceFolder: 'day-trader-java-app/daytrader-kubernetes-manifests'
    globExpressions: '**'