# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
#- task: Maven@3
#  inputs:
#    mavenPomFile: 'day-trader-java-app/pom.xml'
#    publishJUnitResults: false
#    javaHomeOption: 'JDKVersion'
#    mavenVersionOption: 'Default'
#    mavenAuthenticateFeed: false
#    effectivePomSkip: false
#    sonarQubeRunAnalysis: false
#
#- task: Docker@2
#  displayName: 'daytrader-accounts'
#  inputs:
#    containerRegistry: 'Azure-Puneet'
#    repository: 'daytrader-accounts'
#    tags: '15'
#    command: 'buildAndPush'
#    Dockerfile: 'day-trader-java-app/daytrader-example-accountsrepo/daytrader-accountsapp/daytrader-accounts/Dockerfile'
#
#- task: Docker@2
#  displayName: 'daytrader-gateway'
#  inputs:
#    containerRegistry: 'Azure-Puneet'
#    repository: 'daytrader-gateway'
#    tags: '15'
#    command: 'buildAndPush'
#    Dockerfile: 'day-trader-java-app/daytrader-example-gatewayrepo/daytrader-gatewayapp/daytrader-gateway/Dockerfile'
#
#
#- task: Docker@2
#  displayName: 'daytrader-portfolios'
#  inputs:
#    containerRegistry: 'Azure-Puneet'
#    repository: 'daytrader-portfolios'
#    tags: '15'
#    command: 'buildAndPush'
#    Dockerfile: 'day-trader-java-app/daytrader-example-portfoliosrepo/daytrader-portfoliosapp/daytrader-portfolios/Dockerfile'
#
#- task: Docker@2
#  displayName: 'daytrader-quotes'
#  inputs:
#    containerRegistry: 'Azure-Puneet'
#    repository: 'daytrader-quotes'
#    tags: '15'
#    command: 'buildAndPush'
#    Dockerfile: 'day-trader-java-app/daytrader-example-quotesrepo/daytrader-quotesapp/daytrader-quotes/Dockerfile'
#
#- task: Docker@2
#  displayName: 'daytrader-web'
#  inputs:
#    containerRegistry: 'Azure-Puneet'
#    repository: 'daytrader-web'
#    tags: '15'
#    command: 'buildAndPush'
#    Dockerfile: 'day-trader-java-app/daytrader-example-webrepo/daytrader-webapp/daytrader-web/Dockerfile'
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Free Trial (7275eafe-1fe0-47d0-89c5-93b73c43e649)'
    azureContainerRegistry: '{"loginServer":"daytrader.azurecr.io", "id" : "/subscriptions/7275eafe-1fe0-47d0-89c5-93b73c43e649/resourceGroups/DayTrader/providers/Microsoft.ContainerRegistry/registries/daytrader"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'up -d'

- task: CmdLine@2
  inputs:
    script: |
      curl --version
      sudo apt-get update && sudo apt-get install --only-upgrade openssl
      curl --version
      curl --sslv3 https://localhost:5443

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Free Trial (7275eafe-1fe0-47d0-89c5-93b73c43e649)'
    azureContainerRegistry: '{"loginServer":"daytrader.azurecr.io", "id" : "/subscriptions/7275eafe-1fe0-47d0-89c5-93b73c43e649/resourceGroups/DayTrader/providers/Microsoft.ContainerRegistry/registries/daytrader"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'down'