trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '3d034576-aa51-4760-88fd-3fe8617a5399'
    definition: '9'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    targetPath: '$(system.defaultworkingdirectory)'

- task: Docker@2
  displayName: 'daytrader-accounts'
  inputs:
    containerRegistry: 'Azure-Puneet'
    repository: 'daytrader-accounts'
    tags: '15'
    command: 'buildAndPush'
    Dockerfile: 'day-trader-java-app/daytrader-example-accountsrepo/daytrader-accountsapp/daytrader-accounts/Dockerfile'

- task: Docker@2
  displayName: 'daytrader-gateway'
  inputs:
    containerRegistry: 'Azure-Puneet'
    repository: 'daytrader-gateway'
    tags: '15'
    command: 'buildAndPush'
    Dockerfile: 'day-trader-java-app/daytrader-example-gatewayrepo/daytrader-gatewayapp/daytrader-gateway/Dockerfile'


- task: Docker@2
  displayName: 'daytrader-portfolios'
  inputs:
    containerRegistry: 'Azure-Puneet'
    repository: 'daytrader-portfolios'
    tags: '15'
    command: 'buildAndPush'
    Dockerfile: 'day-trader-java-app/daytrader-example-portfoliosrepo/daytrader-portfoliosapp/daytrader-portfolios/Dockerfile'

- task: Docker@2
  displayName: 'daytrader-quotes'
  inputs:
    containerRegistry: 'Azure-Puneet'
    repository: 'daytrader-quotes'
    tags: '15'
    command: 'buildAndPush'
    Dockerfile: 'day-trader-java-app/daytrader-example-quotesrepo/daytrader-quotesapp/daytrader-quotes/Dockerfile'

- task: Docker@2
  displayName: 'daytrader-web'
  inputs:
    containerRegistry: 'Azure-Puneet'
    repository: 'daytrader-web'
    tags: '15'
    command: 'buildAndPush'
    Dockerfile: 'day-trader-java-app/daytrader-example-webrepo/daytrader-webapp/daytrader-web/Dockerfile'
   