trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

#WIP
- task: PowerShell@2
  inputs:
    filePath: 'day-trader-java-app/daytrader-api-management/CreateAPIMServiceAllMicroservices.ps1'
    failOnStderr: true
    pwsh: true