# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger: none

pool:
  vmImage: 'ubuntu-latest'
  name: Azure Pipelines
  demands: maven


steps:
#JAVA Build
- task: Maven@3
  displayName: 'Java Build'
  inputs:
    mavenPomFile: 'day-trader-java-app/pom.xml'


#- task: MavenAuthenticate@0
#  inputs:
#    artifactsFeeds: 'daytrader2'
#- task: Maven@3
#  inputs:
#    mavenPomFile: 'day-trader-java-app/pom.xml'
#    goals: 'deploy'
#    publishJUnitResults: false
#    javaHomeOption: 'JDKVersion'
#    mavenVersionOption: 'Default'
#    mavenAuthenticateFeed: false
#    effectivePomSkip: false
#    sonarQubeRunAnalysis: false
#- task: CopyFiles@2
#  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
#  inputs:
#    SourceFolder: '$(system.defaultworkingdirectory)'
#    Contents: '**/*.war'
#    TargetFolder: '$(build.artifactstagingdirectory)'
#  condition: succeededOrFailed()
#
#
#- task: PublishBuildArtifacts@1
#  displayName: 'Publish Artifact: drop'
#  inputs:
#    PathtoPublish: '$(build.artifactstagingdirectory)'
#  condition: succeededOrFailed()


#Docker Build and Push to DockerHub
- task: Docker@2
  displayName: 'daytrader-accounts'
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'azseed / daytrader-accounts'
    command: 'buildAndPush'
    Dockerfile: 'day-trader-java-app/daytrader-example-accountsrepo/daytrader-accountsapp/daytrader-accounts/Dockerfile'
    tags: '15'

- task: Docker@2
  displayName: 'daytrader-gateway'
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'azseed / daytrader-gateway'
    command: 'buildAndPush'
    Dockerfile: 'day-trader-java-app/daytrader-example-gatewayrepo/daytrader-gatewayapp/daytrader-gateway/Dockerfile'
    tags: '15'

- task: Docker@2
  displayName: 'daytrader-portfolios'
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'azseed / daytrader-portfolios'
    command: 'buildAndPush'
    Dockerfile: 'day-trader-java-app/daytrader-example-portfoliosrepo/daytrader-portfoliosapp/daytrader-portfolios/Dockerfile'
    tags: '15'

- task: Docker@2
  displayName: 'daytrader-quotes'
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'azseed / daytrader-quotes'
    command: 'buildAndPush'
    Dockerfile: 'day-trader-java-app/daytrader-example-quotesrepo/daytrader-quotesapp/daytrader-quotes/Dockerfile'
    tags: '15'

- task: Docker@2
  displayName: 'daytrader-web'
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'azseed / daytrader-web'
    command: 'buildAndPush'
    Dockerfile: 'day-trader-java-app/daytrader-example-webrepo/daytrader-webapp/daytrader-web/Dockerfile'
    tags: '15'


#Deploy to AKS
- task: Kubernetes@1
  displayName: 'daytrader-accounts-deployment-k8s'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'daytrader-cluster-srv-conn'
    command: 'apply'
    arguments: '-f kubernetes-manifests/accounts/deployment.yaml'
    secretType: 'dockerRegistry'

- task: Kubernetes@1
  displayName: 'daytrader-accounts-service-k8s'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'daytrader-cluster-srv-conn'
    command: 'apply'
    arguments: '-f kubernetes-manifests/accounts/service.yaml'

- task: Kubernetes@1
  displayName: 'daytrader-gateway-deployment-k8s'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'daytrader-cluster-srv-conn'
    command: 'apply'
    arguments: '-f kubernetes-manifests/gateway/deployment.yaml'

- task: Kubernetes@1
  displayName: 'daytrader-gateway-service-k8s'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'daytrader-cluster-srv-conn'
    command: 'apply'
    arguments: '-f kubernetes-manifests/gateway/service.yaml'

- task: Kubernetes@1
  displayName: 'daytrader-portfolios-deployment-k8s'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'daytrader-cluster-srv-conn'
    command: 'apply'
    arguments: '-f kubernetes-manifests/portfolios/deployment.yaml'

- task: Kubernetes@1
  displayName: 'daytrader-portfolios-service-k8s'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'daytrader-cluster-srv-conn'
    command: 'apply'
    arguments: '-f kubernetes-manifests/portfolios/service.yaml'

- task: Kubernetes@1
  displayName: 'daytrader-quotes-deployment-k8s'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'daytrader-cluster-srv-conn'
    command: 'apply'
    arguments: '-f kubernetes-manifests/quotes/deployment.yaml'

- task: Kubernetes@1
  displayName: 'daytrader-quotes-service-k8s'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'daytrader-cluster-srv-conn'
    command: 'apply'
    arguments: '-f kubernetes-manifests/quotes/service.yaml'

- task: Kubernetes@1
  displayName: 'daytrader-web-deployment-k8s'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'daytrader-cluster-srv-conn'
    command: 'apply'
    arguments: '-f kubernetes-manifests/web/deployment.yaml'

- task: Kubernetes@1
  displayName: 'daytrader-web-service-k8s'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'daytrader-cluster-srv-conn'
    command: 'apply'
    arguments: '-f kubernetes-manifests/web/service.yaml'

#- task: Kubernetes@1
#  inputs:
#    connectionType: 'Kubernetes Service Connection'
#    kubernetesServiceEndpoint: 'daytrader-cluster-srv-conn'
#    command: 'apply'
#    arguments: '-f kubernetes-manifests/ingress/ingress.yaml'
#    secretType: 'dockerRegistry'


#EKS Deploy
#- task: DownloadSecureFile@1
#  name: fullchain
#  inputs:
#    secureFile: 'fullchain.pem'
#
#- task: DownloadSecureFile@1
#  name: privkey
#  inputs:
#    secureFile: 'privkey.pem'
#
#- task: CmdLine@2
#  inputs:
#    script: 'cat $(privkey.secureFilePath) $(fullchain.secureFilePath)'
#
#- task: Kubernetes@1
#  inputs:
#    connectionType: 'Kubernetes Service Connection'
#    kubernetesServiceEndpoint: 'daytrader-cluster-srv-conn'
#    command: 'create'
#    arguments: 'secret tls daytrader-tls-secret --key $(privkey.secureFilePath) --cert $(fullchain.secureFilePath)'
#    secretType: 'dockerRegistry'


#Testing
#- task: Bash@3
#  inputs:
#    filePath: 'day-trader-java-app/daytrader-postman-testing/test_all.sh'
#    workingDirectory: 'day-trader-java-app/daytrader-postman-testing/'
#    failOnStderr: true

#- task: PublishTestResults@2
#  inputs:
#    testResultsFormat: 'JUnit'
#    testResultsFiles: 'day-trader-java-app/daytrader-postman-testing/**.xml'
#    mergeTestResults: true
