apiVersion: v1
kind: Service
metadata:
  labels:
    app: daytrader-trade-producer
  name: daytrader-trade-producer
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 7453
  selector:
    app: daytrader-trade-producer
  #sessionAffinity: ClientIP
#  type: LoadBalancer 
