spring:
  kafka:
    bootstrap-servers: localhost:9092
  
app:
  topic:
    example: example.t

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.memorynotfound: DEBUG
url: ${DAYTRADER-GATEWAY:https://localhost}:2443/portfolios/{uid}/orders?mode=