apiVersion: v1
kind: Service
metadata:
  labels:
    app: daytrader-web-react
  name: daytrader-web-react
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: daytrader-web-react
  sessionAffinity: ClientIP
#  type: NodePort
  type: LoadBalancer
