version: '3.4'

services:
  daytrader-container:
    image: singhavinash857/daytrader-container-mfe:latest
    ports:
      - "3001:3001"
    restart: always  
    environment:
      - DAYTRADER_ACCOUNTS_SERVICE=https://daytrader-accounts:1443
      - DAYTRADER_GATEWAY_SERVICE=https://daytrader-gateway:2443
      - DAYTRADER_PORTFOLIOS_SERVICE=https://daytrader-portfolios:3443
      - DAYTRADER_QUOTES_SERVICE=https://daytrader-quotes:4443
   

  daytrader-account:
    image: singhavinash857/daytrader-account-mfe:latest
    ports:
      - "3002:3002"
    restart: always
    environment:
      - DAYTRADER_ACCOUNTS_SERVICE=https://daytrader-accounts:1443
      - DAYTRADER_GATEWAY_SERVICE=https://daytrader-gateway:2443
      - DAYTRADER_PORTFOLIOS_SERVICE=https://daytrader-portfolios:3443
      - DAYTRADER_QUOTES_SERVICE=https://daytrader-quotes:4443

  daytrader-portfolio:
    image: singhavinash857/daytrader-portfolio-mfe:latest
    ports:
      - "3003:3003"
    restart: always
    environment:
      - DAYTRADER_ACCOUNTS_SERVICE=https://daytrader-accounts:1443
      - DAYTRADER_GATEWAY_SERVICE=https://daytrader-gateway:2443
      - DAYTRADER_PORTFOLIOS_SERVICE=https://daytrader-portfolios:3443
      - DAYTRADER_QUOTES_SERVICE=https://daytrader-quotes:4443
  
  daytrader-quotes:
    image: singhavinash857/daytrader-quotes-mfe:latest
    ports:
      - "3004:3004"
    restart: always
    environment:
      - DAYTRADER_ACCOUNTS_SERVICE=https://daytrader-accounts:1443
      - DAYTRADER_GATEWAY_SERVICE=https://daytrader-gateway:2443
      - DAYTRADER_PORTFOLIOS_SERVICE=https://daytrader-portfolios:3443
      - DAYTRADER_QUOTES_SERVICE=https://daytrader-quotes:4443
 