version: '3.5'

services:
  daytrader-container-mfe:
    image: azseed/daytrader-web-mfe-container-static:0
    ports:
      - "3001:80"
    restart: always  
    environment:
      - REACT_APP_DAYTRADER_GATEWAY_SERVICE=https://localhost:2443
      - REACT_APP_DAYTRADER_ACCOUNT_MFE_URL=http://localhost:3002
      - REACT_APP_DAYTRADER_PORTFOLIO_MFE_URL=http://localhost:3003  
      - REACT_APP_DAYTRADER_QUOTES_MFE_URL=http://localhost:3004 

  daytrader-account-mfe:
    image: azseed/daytrader-web-mfe-accounts-static:0
    ports:
      - "3002:80"
    restart: always
    environment:
      - REACT_APP_DAYTRADER_GATEWAY_SERVICE=https://localhost:2443

  daytrader-portfolio-mfe:
    image: azseed/daytrader-web-mfe-portfolios-static:0
    ports:
      - "3003:80"
    restart: always
    environment:
      - REACT_APP_DAYTRADER_GATEWAY_SERVICE=https://localhost:2443

  
  daytrader-quotes-mfe:
    image: azseed/daytrader-web-mfe-quotes-static:0
    ports:
      - "3004:80"
    restart: always
    environment:
      - REACT_APP_DAYTRADER_GATEWAY_SERVICE=https://localhost:2443
