apiVersion: v1
kind: Service
metadata:
  labels:
    app: daytrader-web
  name: daytrader-web
  namespace: default
spec:
  ports:
  - port: 81
    protocol: TCP
    targetPort: 5443
  selector:
    app: daytrader-web
  sessionAffinity: ClientIP
#  type: NodePort
  type: LoadBalancer
