apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: daytrader-accounts
  name: daytrader-accounts
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daytrader-accounts
  template:
    metadata:
      labels:
        app: daytrader-accounts
    spec:
      containers:
      - name: daytrader-accounts
        image: tnshibu/daytrader-accounts:1.6
        imagePullPolicy: Always
        ports:
        - containerPort: 1443
          protocol: TCP
#        readinessProbe:  
#          httpGet:
#            path: /health
#            scheme: HTTP
#            port: 1443
#          initialDelaySeconds: 30
#          periodSeconds: 30
#          timeoutSeconds: 10
#        livenessProbe:  
#          httpGet:
#            path: /health
#            scheme: HTTP
#            port: 1443
#          initialDelaySeconds: 30
#          periodSeconds: 30
#          timeoutSeconds: 11
#          failureThreshold: 4
        env:
        - name: DAYTRADER_ACCOUNTS_SERVICE
          value: http://daytrader-accounts
        - name: DAYTRADER_GATEWAY_SERVICE
          value: http://daytrader-gateway
        - name: DAYTRADER_PORTFOLIOS_SERVICE
          value: http://daytrader-portfolios
        - name: DAYTRADER_QUOTES_SERVICE
          value: http://daytrader-quotes
        - name: GET_HOSTS_FROM
          value: dns
#       DATABASE related config
        - name: DAYTRADER_DATABASE_DRIVER
          valueFrom:
            configMapKeyRef:
              name: daytrader-accounts-config-map
              key: DAYTRADER_DATABASE_DRIVER
        - name: DAYTRADER_DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: daytrader-accounts-config-map
              key: DAYTRADER_DATABASE_URL
        - name: DAYTRADER_DATABASE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: daytrader-accounts-config-map
              key: DAYTRADER_DATABASE_USERNAME
        - name: DAYTRADER_DATABASE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: daytrader-accounts-config-map
              key: DAYTRADER_DATABASE_PASSWORD
