version: '3.4'

services:
      
  daytrader-auth-server:
    image: azseed/daytrader-auth-server:2.1
    ports:
      - "1555:1555"
    restart: always
    environment:
      - DAYTRADER_DATABASE_DRIVER=org.apache.derby.jdbc.EmbeddedDriver
      - DAYTRADER_DATABASE_URL=jdbc:derby:authdb;create=true
      - DAYTRADER_DATABASE_USERNAME=dummy
      - DAYTRADER_DATABASE_PASSWORD=dummy

  daytrader-accounts:
    image: azseed/daytrader-accounts:2.1
    ports:
      - "1443:1443"
    restart: always
    depends_on:
      - daytrader-auth-server
      - daytrader-portfolios
      - daytrader-quotes
      
    environment:
      - DAYTRADER_ACCOUNTS_SERVICE=http://daytrader-accounts:1443
      - DAYTRADER_GATEWAY_SERVICE=http://daytrader-gateway:2443
      - DAYTRADER_PORTFOLIOS_SERVICE=http://daytrader-portfolios:3443
      - DAYTRADER_QUOTES_SERVICE=http://daytrader-quotes:4443
      - DAYTRADER_AUTH_SERVICE=http://daytrader-auth-server:1555
      - DAYTRADER_DATABASE_DRIVER=org.apache.derby.jdbc.EmbeddedDriver
      - DAYTRADER_DATABASE_URL=jdbc:derby:tradesdb;create=true
      - DAYTRADER_DATABASE_USERNAME=dummy
      - DAYTRADER_DATABASE_PASSWORD=dummy      

  daytrader-gateway:
    image: azseed/daytrader-gateway:2.1
    ports:
      - "2443:2443"
    restart: always
    depends_on:
      - daytrader-auth-server
      - daytrader-accounts
      - daytrader-portfolios
      - daytrader-quotes
    environment:
      - DAYTRADER_ACCOUNTS_SERVICE=http://daytrader-accounts:1443
      - DAYTRADER_GATEWAY_SERVICE=http://daytrader-gateway:2443
      - DAYTRADER_PORTFOLIOS_SERVICE=http://daytrader-portfolios:3443
      - DAYTRADER_QUOTES_SERVICE=http://daytrader-quotes:4443
      - DAYTRADER_AUTH_SERVICE=http://daytrader-auth-server:1555

  daytrader-portfolios:
    image: azseed/daytrader-portfolios:2.1
    ports:
      - "3443:3443"
    restart: always
    depends_on:
      - daytrader-auth-server
      - daytrader-quotes
    environment:
      - DAYTRADER_ACCOUNTS_SERVICE=http://daytrader-accounts:1443
      - DAYTRADER_GATEWAY_SERVICE=http://daytrader-gateway:2443
      - DAYTRADER_PORTFOLIOS_SERVICE=http://daytrader-portfolios:3443
      - DAYTRADER_QUOTES_SERVICE=http://daytrader-quotes:4443
      - DAYTRADER_AUTH_SERVICE=http://daytrader-auth-server:1555
      - DAYTRADER_DATABASE_DRIVER=org.apache.derby.jdbc.EmbeddedDriver
      - DAYTRADER_DATABASE_URL=jdbc:derby:tradesdb;create=true
      - DAYTRADER_DATABASE_USERNAME=dummy
      - DAYTRADER_DATABASE_PASSWORD=dummy      
  daytrader-quotes:
    image: azseed/daytrader-quotes:2.1
    ports:
      - "4443:4443"
    restart: always
    depends_on:
      - daytrader-auth-server
    environment:
      - DAYTRADER_ACCOUNTS_SERVICE=http://daytrader-accounts:1443
      - DAYTRADER_GATEWAY_SERVICE=http://daytrader-gateway:2443
      - DAYTRADER_PORTFOLIOS_SERVICE=http://daytrader-portfolios:3443
      - DAYTRADER_QUOTES_SERVICE=http://daytrader-quotes:4443
      - DAYTRADER_AUTH_SERVICE=http://daytrader-auth-server:1555
      - DAYTRADER_DATABASE_DRIVER=org.apache.derby.jdbc.EmbeddedDriver
      - DAYTRADER_DATABASE_URL=jdbc:derby:tradesdb;create=true
      - DAYTRADER_DATABASE_USERNAME=dummy
      - DAYTRADER_DATABASE_PASSWORD=dummy      
      
  daytrader-web:
    image: azseed/daytrader-web:2.1
    environment:
      - DAYTRADER_ACCOUNTS_SERVICE=http://daytrader-accounts:1443
      - DAYTRADER_GATEWAY_SERVICE=http://daytrader-gateway:2443
      - DAYTRADER_PORTFOLIOS_SERVICE=http://daytrader-portfolios:3443
      - DAYTRADER_QUOTES_SERVICE=http://daytrader-quotes:4443
      - DAYTRADER_AUTH_SERVICE=http://daytrader-auth-server:1555
      
    ports:
      - "5443:5443"
    restart: always

    depends_on:
      - daytrader-accounts
      - daytrader-gateway
      - daytrader-portfolios
      - daytrader-quotes
      - daytrader-auth-server
    
#-------------- reactJS - micro-frontend - static - start -----------------------------------------------
  daytrader-web-mfe-container-static:
    image: azseed/daytrader-web-mfe-container-static:2.1
    ports:
      - "4001:3001"
    restart: always  
    environment:
      - REACT_APP_DAYTRADER_GATEWAY_SERVICE=http://localhost:2443
      - REACT_APP_DAYTRADER_ACCOUNT_MFE_URL=http://localhost:4002
      - REACT_APP_DAYTRADER_PORTFOLIO_MFE_URL=http://localhost:4003  
      - REACT_APP_DAYTRADER_QUOTES_MFE_URL=http://localhost:4004 

  daytrader-web-mfe-accounts-static:
    image: azseed/daytrader-web-mfe-accounts-static:2.1
    ports:
      - "4002:3002"
    restart: always
    environment:
      - REACT_APP_DAYTRADER_GATEWAY_SERVICE=http://localhost:2443


  daytrader-web-mfe-portfolios-static:
    image: azseed/daytrader-web-mfe-portfolios-static:2.1
    ports:
      - "4003:3003"
    restart: always
    environment:
      - REACT_APP_DAYTRADER_GATEWAY_SERVICE=http://localhost:2443

  
  daytrader-web-mfe-quotes-static:
    image: azseed/daytrader-web-mfe-quotes-static:2.1
    ports:
      - "4004:3004"
    restart: always
    environment:
      - REACT_APP_DAYTRADER_GATEWAY_SERVICE=http://localhost:2443
#-------------- reactJS - micro-frontend - static - end -------------------------------------------------
