apiVersion: v1
kind: Service
metadata:
  labels:
    app: daytrader-scdf-trade-generator
  name: daytrader-scdf-trade-generator
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 6443
  selector:
    app: daytrader-scdf-trade-generator
  #sessionAffinity: ClientIP
#  type: LoadBalancer 
