apiVersion: v1
kind: Service
metadata:
  labels:
    app: daytrader-web-react-static
  name: daytrader-web-react-static
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: daytrader-web-react-static
  sessionAffinity: ClientIP
  type: NodePort
#  type: LoadBalancer
