server:
  port: 7443

url: ${DAYTRADER_GATEWAY_SERVICE:https://localhost:2443}/portfolios/{uid}/orders?mode=

spring:
  application:
    name: "stock-tick-consumer-avro"

  kafka:
    bootstrap-servers: pkc-lgwgm.eastus2.azure.confluent.cloud:9092
    properties:
      ssl.endpoint.identification.algorithm: https
      sasl.mechanism: PLAIN
      request.timeout.ms: 120000
      security.protocol: SASL_SSL
      retry.backoff.ms: 500
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="SQBFW4EG47FHFWSI" password="qzbQtcO+gN/IlsU4h7vJhwzb1waKAHJVdsxejVhnfL+4YQamXP09OU81LVm+b0i3";
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.ofss.daytrader.trade.consumer.ConsumerDeserializer 
      #org.springframework.kafka.support.serializer.JsonDeserializer
      #org.apache.kafka.common.serialization.StringDeserializer
      client-id: ${spring.application.name}
      auto-offset-reset: earliest
      group-id: kafkaSchemaGroup
      properties:
        spring:
          json:
            trusted:
              packages: "*"

    # At application startup a missing topic on the broker will not fail the
    # application startup
    listener:
      missing-topics-fatal: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
