apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: daytrader-quotes
  name: daytrader-quotes
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daytrader-quotes
  template:
    metadata:
      labels:
        app: daytrader-quotes
    spec:
      containers:
      - name: daytrader-quotes
        image: azseed/daytrader-quotes:2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 4443
          protocol: TCP
#        readinessProbe:  
#          httpGet:
#            path: /health
#            scheme: HTTP
#            port: 4443
#          initialDelaySeconds: 30
#          periodSeconds: 30
#          timeoutSeconds: 10
#        livenessProbe:  
#          httpGet:
#            path: /health
#            scheme: HTTP
#            port: 4443
#          initialDelaySeconds: 30
#          periodSeconds: 30
#          timeoutSeconds: 10
#          failureThreshold: 4
        env:
        #----service urls - start --------------
        - name: DAYTRADER_ACCOUNTS_SERVICE
          valueFrom:
            configMapKeyRef:
              name: daytrader-service-urls-config-map
              key: DAYTRADER_ACCOUNTS_SERVICE
        - name: DAYTRADER_GATEWAY_SERVICE
          valueFrom:
            configMapKeyRef:
              name: daytrader-service-urls-config-map
              key: DAYTRADER_GATEWAY_SERVICE
        - name: DAYTRADER_PORTFOLIOS_SERVICE
          valueFrom:
            configMapKeyRef:
              name: daytrader-service-urls-config-map
              key: DAYTRADER_PORTFOLIOS_SERVICE
        - name: DAYTRADER_QUOTES_SERVICE
          valueFrom:
            configMapKeyRef:
              name: daytrader-service-urls-config-map
              key: DAYTRADER_QUOTES_SERVICE
        #----service urls - end ----------------
        #----DATABASE related - start ----------
        - name: DAYTRADER_DATABASE_DRIVER
          valueFrom:
            configMapKeyRef:
              name: daytrader-quotes-db-config-map
              key: DAYTRADER_DATABASE_DRIVER
        - name: DAYTRADER_DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: daytrader-quotes-db-config-map
              key: DAYTRADER_DATABASE_URL
        - name: DAYTRADER_DATABASE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: daytrader-quotes-db-config-map
              key: DAYTRADER_DATABASE_USERNAME
        - name: DAYTRADER_DATABASE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: daytrader-quotes-db-config-map
              key: DAYTRADER_DATABASE_PASSWORD
        - name: DAYTRADER_DATABASE_DIALECT
          valueFrom:
            configMapKeyRef:
              name: daytrader-quotes-db-config-map
              key: DAYTRADER_DATABASE_DIALECT
        #----DATABASE related - end ------------
        #----application config - started ------
        - name: GET_HOSTS_FROM
          value: dns
        - name: SERVER_SSL_ENABLED
          valueFrom:
            configMapKeyRef:
              name: config-map-application-properties
              key: SERVER_SSL_ENABLED
        - name: DAYTRADER_OAUTH_ENABLE
          valueFrom:
            configMapKeyRef:
              name: config-map-application-properties
              key: DAYTRADER_OAUTH_ENABLE
        #----application config - end ----------
