apiVersion: v1
kind: Service
metadata:
  labels:
    app: daytrader-web-mfe-container-static
  name: daytrader-web-mfe-container-static
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: daytrader-web-mfe-container-static
  sessionAffinity: ClientIP
#  type: NodePort
  type: LoadBalancer
