apiVersion: autoscaling/v2beta2
#apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: daytrader-gateway-hpa
spec:
  maxReplicas: 5 # define max replica count
  minReplicas: 1  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: daytrader-gateway
#  targetCPUUtilizationPercentage: 5 # target CPU utilization
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30