apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: daytrader-report-generator
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: daytrader-report-generator
            image: tnshibu/daytrader-report-generator:1.0
            imagePullPolicy: Always
#            args:
#            - /bin/sh
#            - -c
#            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure