apiVersion: v1
kind: Service
metadata:
  labels:
    app: daytrader-accounts
  name: daytrader-accounts
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 1443
  selector:
    app: daytrader-accounts
  #sessionAffinity: ClientIP
  type: LoadBalancer 
