apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: daytrader-auth-server-hpa
spec:
  maxReplicas: 5 # define max replica count
  minReplicas: 1  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: daytrader-auth-server
  targetCPUUtilizationPercentage: 2 # target CPU utilization
