apiVersion: v1
kind: Service
metadata:
  labels:
    app: daytrader-trade-consumer
  name: daytrader-trade-consumer
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 7443
  selector:
    app: daytrader-trade-consumer
  #sessionAffinity: ClientIP
#  type: LoadBalancer 
