apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: daytrader-auth-server
  name: daytrader-auth-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daytrader-auth-server
  template:
    metadata:
      labels:
        app: daytrader-auth-server
    spec:
      containers:
      - name: daytrader-auth-server
        image: azseed/daytrader-auth-server:1.8
        imagePullPolicy: Always
        ports:
        - containerPort: 1555
          protocol: TCP
#        readinessProbe:  
#          httpGet:
#            path: /health
#            scheme: HTTP
#            port: 1443
#          initialDelaySeconds: 30
#          periodSeconds: 30
#          timeoutSeconds: 10
#        livenessProbe:  
#          httpGet:
#            path: /health
#            scheme: HTTP
#            port: 1443
#          initialDelaySeconds: 30
#          periodSeconds: 30
#          timeoutSeconds: 11
#          failureThreshold: 4
        env:
        #----service urls - start --------------
        
        - name: DAYTRADER_AUTH_SERVICE
          valueFrom:
            configMapKeyRef:
              name: daytrader-service-urls-config-map
              key: DAYTRADER_AUTH_SERVICE
        - name: DAYTRADER_ACCOUNTS_SERVICE
          valueFrom:
            configMapKeyRef:
              name: daytrader-service-urls-config-map
              key: DAYTRADER_ACCOUNTS_SERVICE
#        - name: DAYTRADER_GATEWAY_SERVICE
#          valueFrom:
#            configMapKeyRef:
#              name: daytrader-service-urls-config-map
#              key: DAYTRADER_GATEWAY_SERVICE
#        - name: DAYTRADER_PORTFOLIOS_SERVICE
#          valueFrom:
#            configMapKeyRef:
#              name: daytrader-service-urls-config-map
#              key: DAYTRADER_PORTFOLIOS_SERVICE
#        - name: DAYTRADER_QUOTES_SERVICE
#          valueFrom:
#            configMapKeyRef:
#              name: daytrader-service-urls-config-map
#              key: DAYTRADER_QUOTES_SERVICE
        #----service urls - end ----------------
        #----DATABASE related - start ----------
        - name: DAYTRADER_DATABASE_DRIVER
          valueFrom:
            configMapKeyRef:
              name: daytrader-auth-db-config-map
              key: DAYTRADER_DATABASE_DRIVER
        - name: DAYTRADER_DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: daytrader-auth-db-config-map
              key: DAYTRADER_DATABASE_URL
        - name: DAYTRADER_DATABASE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: daytrader-auth-db-config-map
              key: DAYTRADER_DATABASE_USERNAME
        - name: DAYTRADER_DATABASE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: daytrader-auth-db-config-map
              key: DAYTRADER_DATABASE_PASSWORD
        - name: DAYTRADER_DATABASE_DIALECT
          valueFrom:
            configMapKeyRef:
              name: daytrader-accounts-db-config-map
              key: DAYTRADER_DATABASE_DIALECT
        #----DATABASE related - end ------------
        #----application config - started ------
        - name: GET_HOSTS_FROM
          value: dns
        - name: SERVER_SSL_ENABLED
          valueFrom:
            configMapKeyRef:
              name: config-map-application-properties
              key: SERVER_SSL_ENABLED
        #----application config - end ----------
