apiVersion: v1
kind: Service
metadata:
  labels:
    app: daytrader-auth-server
  name: daytrader-auth-server
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 1555
  selector:
    app: daytrader-auth-server
  #sessionAffinity: ClientIP
  type: LoadBalancer 
