apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: daytrader-web
  name: daytrader-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daytrader-web
  template:
    metadata:
      labels:
        app: daytrader-web
    spec:
      containers:
      - name: daytrader-web
        image: azseed/daytrader-web:17.2
        imagePullPolicy: Always
        ports:
        - containerPort: 5443
          protocol: TCP
#        readinessProbe:  
#          httpGet:
#            path: /health
#            scheme: HTTP
#            port: 5443
#          initialDelaySeconds: 30
#          periodSeconds: 30
#          timeoutSeconds: 10
#        livenessProbe:  
#          httpGet:
#            path: /health
#            scheme: HTTP
#            port: 5443
#          initialDelaySeconds: 30
#          periodSeconds: 30
#          timeoutSeconds: 10
#          failureThreshold: 4
        env:
        - name: DAYTRADER_ACCOUNTS_SERVICE
          valueFrom:
            configMapKeyRef:
              name: daytrader-service-urls-config-map
              key: DAYTRADER_ACCOUNTS_SERVICE
        - name: DAYTRADER_GATEWAY_SERVICE
          valueFrom:
            configMapKeyRef:
              name: daytrader-service-urls-config-map
              key: DAYTRADER_GATEWAY_SERVICE
        - name: DAYTRADER_PORTFOLIOS_SERVICE
          valueFrom:
            configMapKeyRef:
              name: daytrader-service-urls-config-map
              key: DAYTRADER_PORTFOLIOS_SERVICE
        - name: DAYTRADER_QUOTES_SERVICE
          valueFrom:
            configMapKeyRef:
              name: daytrader-service-urls-config-map
              key: DAYTRADER_QUOTES_SERVICE
        - name: GET_HOSTS_FROM
          value: dns
        - name: SERVER_SSL_ENABLED
          value: "false"
