apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: daytrader-web-mfe-portfolios-static
  name: daytrader-web-mfe-portfolios-static
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daytrader-web-mfe-portfolios-static
  template:
    metadata:
      labels:
        app: daytrader-web-mfe-portfolios-static
    spec:
      containers:
      - name: daytrader-web-mfe-portfolios-static
        image: azseed/daytrader-web-mfe-portfolios-static:2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3003
          protocol: TCP
#        readinessProbe:  
#          httpGet:
#            path: /
#            scheme: HTTP
#            port: 3000
#          initialDelaySeconds: 30
#          periodSeconds: 30
#          timeoutSeconds: 10
#        livenessProbe:  
#          httpGet:
#            path: /
#            scheme: HTTP
#            port: 3000
#          initialDelaySeconds: 30
#          periodSeconds: 30
#          timeoutSeconds: 10
#          failureThreshold: 4
        env:
        - name: CI
          value: "true"
        #----micro-frontend - start ------------
        - name: REACT_APP_DAYTRADER_GATEWAY_SERVICE
          valueFrom:
            configMapKeyRef:
              name: daytrader-service-urls-config-map
              key: REACT_APP_DAYTRADER_GATEWAY_SERVICE
        #----micro-frontend - end --------------
